<?php

return [
    'palettes' => [
        'tuscan' => [
            'name' => 'Jardín Toscano',
            'subtitle' => 'Boda · Cálido & sofisticado',
            'bg' => '#FAF9F6',
            'surface' => '#FFFFFF',
            'surfaceAlt' => '#F3EFE6',
            'ink' => '#2A241D',
            'inkSoft' => '#5C5247',
            'inkMuted' => '#8B7F71',
            'rule' => '#E6DDCB',
            'accent' => '#B08A5B',
            'accentSoft' => '#D9C29B',
            'accentInk' => '#7A5A2E',
            'leaf' => '#6B7A4F',
            'sand' => '#EFE6D2',
            'serif' => '"Playfair Display", "Cormorant Garamond", Georgia, serif',
            'sans' => '"Inter", -apple-system, system-ui, sans-serif',
        ],
        'coastal' => [
            'name' => 'Costa Tulum',
            'subtitle' => 'Boda · Playa relajada',
            'bg' => '#F7F8F6',
            'surface' => '#FFFFFF',
            'surfaceAlt' => '#EAEFEB',
            'ink' => '#1F2B2A',
            'inkSoft' => '#4D5C5A',
            'inkMuted' => '#84938F',
            'rule' => '#D8E0DA',
            'accent' => '#6E9889',
            'accentSoft' => '#B6CBC2',
            'accentInk' => '#446A5C',
            'leaf' => '#3F6155',
            'sand' => '#E5E9DC',
            'serif' => '"Cormorant Garamond", Georgia, serif',
            'sans' => '"Inter", system-ui, sans-serif',
        ],
        'sweet16' => [
            'name' => 'XV Rosé',
            'subtitle' => 'XV años · Rosa & coral',
            'bg' => '#FFF7F4',
            'surface' => '#FFFFFF',
            'surfaceAlt' => '#FAE8E1',
            'ink' => '#3A1F26',
            'inkSoft' => '#6B4750',
            'inkMuted' => '#9F7882',
            'rule' => '#F1D9D2',
            'accent' => '#D87C7E',
            'accentSoft' => '#F0BFB6',
            'accentInk' => '#A24A52',
            'leaf' => '#B57E89',
            'sand' => '#F8E0DA',
            'serif' => '"Playfair Display", Georgia, serif',
            'sans' => '"Inter", system-ui, sans-serif',
        ],
        'noche' => [
            'name' => 'Noche Cumpleaños',
            'subtitle' => 'Cumpleaños · Oscuro & festivo',
            'bg' => '#15131A',
            'surface' => '#1E1B23',
            'surfaceAlt' => '#26222C',
            'ink' => '#F4EFE2',
            'inkSoft' => '#C9C0AD',
            'inkMuted' => '#857C6E',
            'rule' => '#34303A',
            'accent' => '#E5B568',
            'accentSoft' => '#F2D49A',
            'accentInk' => '#F4EFE2',
            'leaf' => '#A8A286',
            'sand' => '#2A2630',
            'serif' => '"Playfair Display", Georgia, serif',
            'sans' => '"Inter", system-ui, sans-serif',
        ],
        'corp' => [
            'name' => 'Corporativo Slate',
            'subtitle' => 'Eventos · Profesional & sobrio',
            'bg' => '#F5F6F8',
            'surface' => '#FFFFFF',
            'surfaceAlt' => '#ECEEF2',
            'ink' => '#11151D',
            'inkSoft' => '#3F4754',
            'inkMuted' => '#7B8392',
            'rule' => '#DCE0E7',
            'accent' => '#2F4858',
            'accentSoft' => '#A6B5C2',
            'accentInk' => '#1A2730',
            'leaf' => '#506470',
            'sand' => '#E4E7EC',
            'serif' => '"Cormorant Garamond", Georgia, serif',
            'sans' => '"Inter", system-ui, sans-serif',
        ],
    ],
];
